API_HOST_URL: 'localhost'
COURSE_ENROLLMENT:
    ENABLED: true
    TYPE: 'webview'
    WEBVIEW:
        SEARCH_BAR_ENABLED: true
        COURSE_SEARCH_URL: 'localhost'
ENVIRONMENT_DISPLAY_NAME: 'edX'
FEEDBACK_EMAIL_ADDRESS: 'sample@example.com'