API_HOST_URL: 'https://appliedx.amat.com'
COURSE_ENROLLMENT:
    ENABLED: true
    EXTERNAL_COURSE_SEARCH_URL: 'https://appliedx.amat.com/courses'
    COURSE_SEARCH_URL: 'https://appliedx.amat.com/courses'
COURSE_SEARCH_URL: 'https://appliedx.amat.com/courses'
ENVIRONMENT_DISPLAY_NAME: 'AMAT'
FEEDBACK_EMAIL_ADDRESS: 'appliedx_ops@amat.com'