API_HOST_URL: 'https://appliedx.amat.com'
COURSE_ENROLLMENT:
    ENABLED: true
    TYPE: 'native'
    WEBVIEW:
        SEARCH_BAR_ENABLED: true
        COURSE_SEARCH_URL: 'https://appliedx.amat.com/courses'
ENVIRONMENT_DISPLAY_NAME: 'AMAT'
FEEDBACK_EMAIL_ADDRESS: 'appliedx_ops@amat.com'