API_HOST_URL: 'locakHost://?'
COURSE_ENROLLMENT:
    ENABLED: true
    EXTERNAL_COURSE_SEARCH_URL: 'locakHost://courses'
    COURSE_SEARCH_URL: 'locakHost://courses'
COURSE_SEARCH_URL: 'locakHost://?'
ENVIRONMENT_DISPLAY_NAME: 'edX'
FEEDBACK_EMAIL_ADDRESS: 'test@test.com'